spring:
  application:
    name: product
  profiles:
    active: dev

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


product:
  ribbon:
    eureka:
      enabled: true