spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://<RDS-ENDPOINT>:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis-stack
      port: 6379
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

service:
  jwt:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    secret-key: ${JWT_SECRET_KEY}