spring:
  application:
    name: eureka server

#  datasource:
#    url: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: redis-stack
#      port: 6379
#      password: ${REDIS_PASSWORD}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 19090
eureka:
  client:
    register-with-eureka: false # 유레카 서버에 자신을 등록하지 않음
    fetch-registry: false       # 유레카 서버에서 레지스트리를 가져오지 않음
    service-url:
      defaultZone: http://localhost:19090/eureka/ # 유레카 클라이언트가 연결할 기본 URL
  instance:
    hostname: localhost # 유레카 서버 인스턴스의 호스트 이름