spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
      loadbalancer:
        ribbon:
          products:
            servers:
              - localhost:19093
              - localhost:19094
            weights:
              - 70
              - 30
      discovery:
        locator:
          enabled: true
  profiles:
    active: dev

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
