spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true

#  datasource:
#    url: jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    redis:
#      host: redis-stack
#      port: 6379
#      password: ${REDIS_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

server:
  port: 19091

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
